version: '3.2'

services:
    composer:
      build: docker/composer
      container_name: bscrawler-composer
      volumes:
          - .:/app

    webserver:
      image: nginx:alpine
      container_name: bscrawler-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "7777:80"
      links:
       - php-fpm
       - composer

    php-fpm:
      build:
        context: .
        dockerfile: docker/php-fpm/Dockerfile
      container_name: bscrawler-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        - ./docker/php-fpm/pool.conf:/usr/local/etc/php-fpm.d/www.conf
        - ./docker/php-fpm/app_dev.php:/application/web/app_dev.php
