version: '3.2'

services:
    php-fpm:
        build:
          context: .
          dockerfile: docker/php-fpm/Dockerfile
        container_name: bscrawler-php-fpm
        working_dir: /application
        volumes:
            - type: bind
              source: ./
              target: /application
        ports:
            - "7777:8000"
